'use client';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {Suspense,useEffect,useState} from 'react';
import {ArrowRight,Code2,Container,Database,GitBranch,GraduationCap,Layers3,ServerCog,ShieldCheck,Workflow} from 'lucide-react';
import {AppShell} from '@/components/AppShell';
type Skill={id:string;name:string;domain:string;progress:number;status:string};
type Path={id:string;name:string;description:string;skills:string[];progress:number};
const iconFor=(id:string)=>id==='python'||id==='java'?Code2:id==='sql'||id==='spark'||id==='kafka'||id==='airflow'||id==='snowflake'?Database:id==='docker'?Container:id==='kubernetes'?ServerCog:id==='git'?GitBranch:id==='terraform'||id==='cicd'?Workflow:id==='linux'?Layers3:id==='api-testing'||id==='selenium'||id==='test-automation'?ShieldCheck:GraduationCap;
const supportedDomains=new Set(['python','sql','java','linux','docker']);
const skillSteps:Record<string,string[]>={
 python:['Syntax, variables and control flow','Functions, collections and modules','Exceptions, testing and packaging','Async/await and I/O','Concurrency, rate limiting and production patterns'],
 sql:['SELECT, filtering and ordering','Tables, keys and joins','Aggregations and NULL handling','Window functions and analytical SQL','Performance, determinism and production patterns'],
 java:['Syntax, classes and object-oriented basics','Collections, exceptions and interfaces','Threads and synchronization','Visibility, atomicity and volatile','Concurrency, deadlocks and memory-model patterns'],
 linux:['Shell and filesystem basics','Processes, PIDs and parent/child relationships','Permissions, descriptors and networking','Signals and graceful shutdown','Production debugging and diagnostics'],
 docker:['Containers, images and Dockerfiles','Image layers, volumes and networks','Namespaces and isolation','Resource limits and cgroups','Production debugging and image optimization']
};
const normalizeSkill=(value:string|null)=>value==='python-concurrency'?'python':value==='sql-window-functions'?'sql':value==='java.concurrency_memory'?'java':value==='linux.process_signals'?'linux':value==='docker.container_internals'?'docker':value;
function SkillCard({s}:{s:Skill}){const Icon=iconFor(s.id);const href=supportedDomains.has(s.id)?'/app/roadmap?domain='+encodeURIComponent(s.id):'/app/sandboxes';return <Link href={href} className={'panel block p-4 transition '+(s.progress>0?'hover:border-red-200 hover:shadow-md':'')}><div className='flex items-start gap-3'><div className='flex h-9 w-9 items-center justify-center rounded-lg border border-slate-200 bg-slate-50'><Icon className='h-4 w-4 text-red-600'/></div><div className='min-w-0 flex-1'><div className='flex items-center justify-between gap-2'><span className='text-sm font-semibold text-slate-900'>{s.name}</span><span className='text-[10px] font-semibold text-slate-500'>{s.progress}%</span></div><p className='mt-1 text-[11px] text-slate-500'>{s.domain} · {s.status.replace('_',' ')}</p><div className='mt-3 h-1.5 rounded-full bg-slate-100'><div className='h-full rounded-full bg-red-500' style={{width:s.progress+'%'}}/></div></div></div>{!supportedDomains.has(s.id)&&<div className='mt-3 text-[10px] font-semibold uppercase tracking-wider text-red-600'>Hands-on lab coming soon</div>}</Link>}
function PathView({path,skills}:{path:Path;skills:Skill[]}){return <AppShell><div className='mx-auto max-w-4xl'><Link href='/app/roadmap' className='text-xs font-semibold text-red-600'>← All roadmaps</Link><div className='mt-5 flex flex-wrap items-end justify-between gap-5'><div><p className='eyebrow text-red-600'>CAREER ROADMAP</p><h1 className='mt-2 text-3xl font-semibold text-slate-950'>{path.name}</h1><p className='mt-2 max-w-2xl text-sm leading-6 text-slate-600'>{path.description}</p></div><div className='text-right'><p className='text-3xl font-semibold text-slate-950'>{path.progress}%</p><p className='text-xs text-slate-500'>shared progress</p></div></div><div className='mt-5 h-2 rounded-full bg-slate-200'><div className='h-full rounded-full bg-red-600' style={{width:path.progress+'%'}}/></div><div className='mt-7 space-y-3'>{path.skills.map((id,i)=>{const s=skills.find(x=>x.id===id);if(!s)return null;return <div key={id} className='panel p-5'><div className='flex items-start gap-4'><div className='flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-slate-200 bg-slate-50'><span className='text-xs font-semibold text-red-600'>{i+1}</span></div><div className='min-w-0 flex-1'><div className='flex items-center justify-between gap-3'><h2 className='text-sm font-semibold text-slate-900'>{s.name}</h2><span className='text-xs font-semibold text-slate-500'>{s.progress}%</span></div><p className='mt-1 text-[11px] text-slate-500'>{s.domain}</p><div className='mt-3 h-1.5 rounded-full bg-slate-100'><div className='h-full rounded-full bg-red-500' style={{width:s.progress+'%'}}/></div><p className='mt-2 text-xs text-slate-500'>{s.status==='DEMONSTRATED'?'Demonstrated in PATIMA.':s.status==='DEVELOPING'?'Assessed and developing.':s.status==='EVALUATED'?'Evaluated; continue building this skill.':'Not evaluated yet.'}</p></div>{supportedDomains.has(s.id)&&<Link href={'/app/roadmap?domain='+encodeURIComponent(s.id)} className='btn-ghost'>Skill <ArrowRight className='h-3.5 w-3.5'/></Link>}</div></div>})}</div></div></AppShell>}
function SkillView({skill}:{skill:Skill}){const steps=skillSteps[skill.id]||[];return <AppShell><div className='mx-auto max-w-3xl'><Link href='/app/roadmap' className='text-xs font-semibold text-red-600'>← All roadmaps</Link><div className='mt-5 panel p-6'><p className='eyebrow text-red-600'>INDIVIDUAL ROADMAP · {skill.domain}</p><h1 className='mt-2 text-3xl font-semibold text-slate-950'>{skill.name}</h1><p className='mt-2 text-sm leading-6 text-slate-600'>One skill, one progress state. The same progress carries into every career roadmap that uses this skill.</p><div className='mt-7 flex items-end justify-between'><div><p className='text-4xl font-semibold text-slate-950'>{skill.progress}%</p><p className='mt-1 text-xs text-slate-500'>{skill.status.replace('_',' ')}</p></div><span className='pill border-red-200 bg-red-50 text-red-700'>{skill.status}</span></div><div className='mt-4 h-2 rounded-full bg-slate-200'><div className='h-full rounded-full bg-red-600' style={{width:skill.progress+'%'}}/></div>{steps.length>0&&<div className='mt-8 space-y-3'><div><p className='eyebrow text-red-600'>LEARNING STEPS</p><h2 className='mt-1 text-base font-semibold text-slate-900'>Build this skill in sequence</h2></div>{steps.map((step,i)=><div key={step} className='flex items-center gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4'><span className={'flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-semibold '+(i<Math.max(0,Math.ceil(skill.progress/20))-1?'bg-red-600 text-white':'border border-slate-300 bg-white text-slate-500')}>{i+1}</span><span className='text-sm text-slate-700'>{step}</span></div>)}</div>}<div className='mt-7 rounded-xl border border-slate-200 bg-slate-50 p-5'><h2 className='text-sm font-semibold text-slate-900'>How progress carries</h2><p className='mt-2 text-xs leading-5 text-slate-600'>Complete and demonstrate this skill once. PATIMA reuses that progress anywhere the skill is a prerequisite — it is not a separate score for every career path.</p></div></div></div></AppShell>}
function Hub({paths,skills}:{paths:Path[];skills:Skill[]}){return <AppShell><div className='mx-auto max-w-6xl'><p className='eyebrow text-red-600'>ROADMAPS</p><h1 className='mt-2 text-3xl font-semibold text-slate-950'>Build toward a role — or master one skill.</h1><p className='mt-2 max-w-3xl text-sm leading-6 text-slate-600'>Your progress is shared. Demonstrating Python, for example, updates the Python roadmap and contributes automatically to every career path that uses Python.</p><section className='mt-8'><div><p className='eyebrow text-red-600'>CAREER PATHS</p><h2 className='mt-1 text-base font-semibold text-slate-950'>Role-based roadmaps</h2></div><div className='mt-4 grid gap-4 md:grid-cols-2'>{paths.map(p=><Link key={p.id} href={'/app/roadmap?path='+encodeURIComponent(p.id)} className='panel p-5 transition hover:border-red-200 hover:shadow-md'><div className='flex items-center justify-between gap-3'><h3 className='text-sm font-semibold text-slate-900'>{p.name}</h3><span className='text-xs font-semibold text-red-600'>{p.progress}%</span></div><p className='mt-2 text-xs leading-5 text-slate-500'>{p.description}</p><div className='mt-4 h-1.5 rounded-full bg-slate-100'><div className='h-full rounded-full bg-red-500' style={{width:p.progress+'%'}}/></div><p className='mt-3 text-[10px] uppercase tracking-wider text-slate-400'>{p.skills.length} shared skills</p></Link>)}</div></section><section className='mt-8'><div><p className='eyebrow text-red-600'>INDIVIDUAL SKILLS</p><h2 className='mt-1 text-base font-semibold text-slate-950'>Language and tool roadmaps</h2></div><div className='mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3'>{skills.map(s=><SkillCard key={s.id} s={s}/>)}</div></section><section className='mt-8 rounded-2xl border border-red-200 bg-red-50 p-5'><h3 className='text-sm font-semibold text-slate-900'>Absolute beginner?</h3><p className='mt-1 text-xs leading-5 text-slate-600'>Start here, not in an assessment. Learn the path, practice the skills, then return when you are ready to measure what you can demonstrate.</p></section></div></AppShell>}
function RoadmapContent(){const params=useSearchParams();const pathId=params.get('path');const domain=params.get('domain');const [data,setData]=useState<{paths:Path[];skills:Skill[]}>({paths:[],skills:[]});const [loading,setLoading]=useState(true);useEffect(()=>{let alive=true;fetch('/api/candidate/roadmaps',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(alive)setData({paths:Array.isArray(d.paths)?d.paths:[],skills:Array.isArray(d.skills)?d.skills:[]})}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);if(loading)return <AppShell><p className='text-sm text-slate-500'>Loading your roadmap…</p></AppShell>;const path=data.paths.find(p=>p.id===pathId);const skill=data.skills.find(s=>s.id===normalizeSkill(domain));if(path)return <PathView path={path} skills={data.skills}/>;if(skill)return <SkillView skill={skill}/>;return <Hub paths={data.paths} skills={data.skills}/>;}
export default function RoadmapPage(){return <Suspense fallback={<AppShell><p>Loading roadmap…</p></AppShell>}><RoadmapContent/></Suspense>}