'use client';
import {Suspense,useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {AppShell} from '@/components/AppShell';

type FixturePreview={columns:string[];rows:(string|number|null)[][]};
type Question={variantId:string;stepIndex:number;promptMarkdown:string;scenarioEntity:string;fixtureDdl:string;fixturePreview?:FixturePreview;totalQuestions:number;remainingTimeSeconds:number};
type State={closed:boolean;status?:string;assessment?:{slug:string;title:string;description:string};question?:Question;session?:{experience_level:string;current_step:number;expires_at:string}};

function Workspace(){
 const params=useSearchParams(),router=useRouter(),sessionId=params.get('session')||'';
 const[state,setState]=useState<State|null>(null); const[answer,setAnswer]=useState(''); const[loading,setLoading]=useState(true); const[submitting,setSubmitting]=useState(false); const[error,setError]=useState(''); const[startedAt,setStartedAt]=useState<number>(Date.now()); const[seconds,setSeconds]=useState<number|null>(null); const events=useRef<{type:string;at:string}[]>([]);
 const load=async()=>{setLoading(true);setError('');try{const res=await fetch(`/api/assessment/adaptive/session?id=${encodeURIComponent(sessionId)}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load assessment');setState(data);setSeconds(data.question?.remainingTimeSeconds??null);setStartedAt(Date.now());}catch(e){setError(e instanceof Error?e.message:'Unable to load assessment')}finally{setLoading(false)}};
 useEffect(()=>{if(!sessionId){router.replace('/app/assessments');return}load()},[sessionId]);
 useEffect(()=>{if(seconds===null)return;const t=window.setInterval(()=>setSeconds(v=>v===null?null:Math.max(0,v-1)),1000);return()=>window.clearInterval(t)},[seconds!==null]);
 const submit=async()=>{if(!state?.question||!answer.trim()||submitting)return;setSubmitting(true);setError('');events.current.push({type:'SUBMIT',at:new Date().toISOString()});try{const res=await fetch('/api/assessment/adaptive/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,variantId:state.question.variantId,answer,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000))})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to submit answer');if(data.completed){setState({...state,closed:true,status:'VERIFIED',question:undefined});return}setState({...state,question:data.next});setSeconds(data.next.remainingTimeSeconds);setStartedAt(Date.now());setAnswer('');}catch(e){setError(e instanceof Error?e.message:'Unable to submit answer')}finally{setSubmitting(false)}};
 if(loading)return <AppShell><div className="mx-auto max-w-3xl"><p className="eyebrow">ASSESSMENT WORKSPACE</p><h1 className="mt-2 text-2xl font-semibold">Preparing your next question…</h1></div></AppShell>;
 if(error&&!state)return <AppShell><div className="mx-auto max-w-3xl"><p className="panel p-6 text-sm text-rose-300">{error}</p></div></AppShell>;
 if(state?.closed)return <AppShell><div className="mx-auto max-w-3xl"><p className="eyebrow">ASSESSMENT COMPLETE</p><h1 className="mt-2 text-3xl font-semibold">{state.assessment?.title||'Assessment'}</h1><div className="panel mt-6 p-6"><p className="text-sm leading-7 text-slate-400">Your responses have been evaluated and the assessment evidence has been recorded on the server.</p><button className="btn-primary mt-5" onClick={()=>router.push('/app/results')}>View result →</button></div></div></AppShell>;
 const q=state?.question; if(!q)return null;
 return <AppShell><div className="mx-auto max-w-3xl">
  <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{state?.assessment?.title}</p><h1 className="mt-2 text-2xl font-semibold">Adaptive assessment</h1><p className="mt-1 text-sm text-slate-500">Question {q.stepIndex} of {q.totalQuestions}</p></div><div className="text-right text-xs text-slate-500">{seconds!==null&&<><div className={seconds<180?'text-amber-300':'text-slate-500'}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</div><div className="mt-1">remaining</div></>}</div></div>
  <div className="mt-5 h-1 rounded bg-slate-800"><div className="h-full rounded bg-emerald-400" style={{width:`${Math.min(100,(q.stepIndex/q.totalQuestions)*100)}%`}}/></div>
  <div className="panel mt-6 p-6"><p className="text-xs font-medium uppercase tracking-[0.14em] text-emerald-300">Your question</p><div className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-300">{q.promptMarkdown}</div>
   <div className="mt-5 rounded-lg border border-white/10 bg-slate-950/40 p-4"><div className="text-xs uppercase tracking-[0.14em] text-slate-600">Dataset</div><div className="mt-2 text-sm text-slate-400">{q.scenarioEntity}</div>{q.fixturePreview&&<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{q.fixturePreview.columns.map(col=><th key={col} className="border-b border-white/10 px-3 py-2 font-medium text-slate-500">{col}</th>)}</tr></thead><tbody>{q.fixturePreview.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className="border-b border-white/5 px-3 py-2 text-slate-400">{cell===null?'NULL':String(cell)}</td>)}</tr>)}</tbody></table></div>}</div>
   <textarea value={answer} onChange={e=>{setAnswer(e.target.value);events.current.push({type:'EDIT',at:new Date().toISOString()})}} className="textarea mt-6 min-h-52" placeholder="Explain your approach, reasoning, and important edge cases…" aria-label="Your answer"/>
   {error&&<p className="mt-3 text-sm text-rose-300" role="alert">{error}</p>}
   <div className="mt-4 flex items-center justify-between gap-4"><span className="text-xs text-slate-600">The next question adapts to your response and time.</span><button className="btn-primary" disabled={!answer.trim()||submitting||seconds===0} onClick={submit}>{submitting?'Evaluating…':'Submit & continue →'}</button></div>
  </div>
 </div></AppShell>;
}
export default function AssessmentWorkspacePage(){return <Suspense fallback={<AppShell><div className="mx-auto max-w-3xl"><p className="eyebrow">ASSESSMENT WORKSPACE</p><h1 className="mt-2 text-2xl font-semibold">Loading…</h1></div></AppShell>}><Workspace/></Suspense>}