'use client';
import {Suspense,useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';

type FixturePreview={columns:string[];rows:(string|number|null)[][]};
type Question={variantId:string;stepIndex:number;promptMarkdown:string;scenarioEntity:string;fixtureDdl:string;fixturePreview?:FixturePreview;totalQuestions:number;remainingTimeSeconds:number};
type State={closed:boolean;status?:string;assessment?:{slug:string;title:string;description:string};question?:Question;session?:{experience_level:string;current_step:number;expires_at:string}};

function Workspace(){
 const params=useSearchParams(),router=useRouter(),sessionId=params.get('session')||'';
 const[state,setState]=useState<State|null>(null); const[answer,setAnswer]=useState(''); const[showDataset,setShowDataset]=useState(false); const[loading,setLoading]=useState(true); const[submitting,setSubmitting]=useState(false); const[error,setError]=useState(''); const[startedAt,setStartedAt]=useState<number>(Date.now()); const[seconds,setSeconds]=useState<number|null>(null); const[keystrokes,setKeystrokes]=useState(0); const events=useRef<{type:string;at:string}[]>([]);
 const load=async()=>{setLoading(true);setError('');try{const res=await fetch(`/api/assessment/adaptive/session?id=${encodeURIComponent(sessionId)}`,{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load assessment');setState(data);setSeconds(data.question?.remainingTimeSeconds??null);setStartedAt(Date.now());}catch(e){setError(e instanceof Error?e.message:'Unable to load assessment')}finally{setLoading(false)}};
 useEffect(()=>{if(!sessionId){router.replace('/app/assessments');return}load()},[sessionId]);
 useEffect(()=>{
  const violation=(reason:string)=>setError(`Integrity event recorded: ${reason}. Stay on the assessment screen.`);
  const onVisibility=()=>{if(document.hidden)violation('tab/window left')};
  const onBlur=()=>violation('assessment window lost focus');
  const onFullscreen=()=>{if(!document.fullscreenElement&&!state?.closed)violation('fullscreen exited')};
  const block=(e:ClipboardEvent)=>{e.preventDefault();violation('clipboard action blocked')};
  const blockContext=(e:MouseEvent)=>{e.preventDefault();violation('context menu blocked')};
  const key=(e:KeyboardEvent)=>{
   const restricted=e.key==='F12'||(e.ctrlKey&&['l','t','w','r','n','p','u'].includes(e.key.toLowerCase()))||(e.ctrlKey&&e.shiftKey&&['i','j','c'].includes(e.key.toLowerCase()))||(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key));
   if(restricted){e.preventDefault();violation('restricted keyboard shortcut')}
  };
  document.addEventListener('visibilitychange',onVisibility);window.addEventListener('blur',onBlur);document.addEventListener('fullscreenchange',onFullscreen);
  document.addEventListener('copy',block);document.addEventListener('cut',block);document.addEventListener('paste',block);document.addEventListener('contextmenu',blockContext);document.addEventListener('keydown',key);
  return()=>{document.removeEventListener('visibilitychange',onVisibility);window.removeEventListener('blur',onBlur);document.removeEventListener('fullscreenchange',onFullscreen);document.removeEventListener('copy',block);document.removeEventListener('cut',block);document.removeEventListener('paste',block);document.removeEventListener('contextmenu',blockContext);document.removeEventListener('keydown',key)}
 },[state?.closed]);
 useEffect(()=>{if(seconds===null)return;const t=window.setInterval(()=>setSeconds(v=>v===null?null:Math.max(0,v-1)),1000);return()=>window.clearInterval(t)},[seconds!==null]);
 const submit=async()=>{if(!state?.question||!answer.trim()||submitting)return;setSubmitting(true);setError('');events.current.push({type:'SUBMIT',at:new Date().toISOString()});try{const res=await fetch('/api/assessments/submit-step',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId,variantId:state.question.variantId,submittedCode:answer,durationSeconds:Math.max(1,Math.round((Date.now()-startedAt)/1000))})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to submit answer');if(data.status==='COMPLETED'){setState({...state,closed:true,status:'VERIFIED',question:undefined});if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});return}setState({...state,question:data.nextQuestion});setSeconds(data.nextQuestion.remainingTimeSeconds);setStartedAt(Date.now());setAnswer('');}catch(e){setError(e instanceof Error?e.message:'Unable to submit answer')}finally{setSubmitting(false)}};
 if(loading)return <div className="min-h-screen bg-[#071019] text-slate-100 p-4 sm:p-6"><div className="mx-auto max-w-6xl"><p className="eyebrow">ASSESSMENT WORKSPACE</p><h1 className="mt-2 text-2xl font-semibold">Preparing your next question…</h1></div></div>;
 if(error&&!state)return <div className="min-h-screen bg-[#071019] text-slate-100 p-4 sm:p-6"><div className="mx-auto max-w-3xl"><p className="panel p-6 text-sm text-rose-300">{error}</p></div></div>;
 if(state?.closed)return <div className="min-h-screen bg-[#071019] text-slate-100 p-4 sm:p-6"><div className="mx-auto max-w-3xl"><p className="eyebrow">ASSESSMENT COMPLETE</p><h1 className="mt-2 text-3xl font-semibold">{state.assessment?.title||'Assessment'}</h1><div className="panel mt-6 p-6"><p className="text-sm leading-7 text-slate-400">Your responses have been evaluated and the assessment evidence has been recorded on the server.</p><button className="btn-primary mt-5" onClick={()=>router.push('/app/results')}>View result →</button></div></div></div>;
 const q=state?.question; if(!q)return null;
 return <div className="min-h-screen bg-[#071019] text-slate-100 p-4 sm:p-6"><div className="mx-auto max-w-3xl">
  <div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{state?.assessment?.title}</p><h1 className="mt-2 text-2xl font-semibold">Adaptive assessment</h1><p className="mt-1 text-sm text-slate-500">Question {q.stepIndex} of {q.totalQuestions}</p></div><div className="text-right text-xs text-slate-500">{seconds!==null&&<><div className={seconds<180?'text-amber-300':'text-slate-500'}>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</div><div className="mt-1">remaining</div></>}</div></div>
  <div className="mt-5 h-1 rounded bg-slate-800"><div className="h-full rounded bg-emerald-400" style={{width:`${Math.min(100,(q.stepIndex/q.totalQuestions)*100)}%`}}/></div>
  <div className="panel mt-6 p-6"><p className="text-xs font-medium uppercase tracking-[0.14em] text-emerald-300">Your question</p><div className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-300">{q.promptMarkdown}</div>
   <div className="mt-5 rounded-lg border border-white/10 bg-slate-950/40 p-4"><div className="flex items-center justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.14em] text-slate-600">SQL dataset</div><div className="mt-2 text-sm text-slate-300">{q.scenarioEntity}</div></div><button type="button" onClick={()=>setShowDataset(v=>!v)} className="rounded-md border border-white/10 px-3 py-2 text-xs text-slate-400 hover:text-slate-200">{showDataset?'Hide dataset':'Show dataset'}</button></div>{showDataset&&<div className="mt-4 space-y-4"><div><div className="mb-2 text-xs font-medium uppercase tracking-[0.14em] text-slate-600">Table definition</div><pre className="overflow-x-auto rounded-lg border border-white/10 bg-black/20 p-4 text-xs leading-5 text-slate-400">{q.fixtureDdl}</pre></div>{q.fixturePreview&&<div><div className="mb-2 text-xs font-medium uppercase tracking-[0.14em] text-slate-600">Sample data</div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{q.fixturePreview.columns.map(col=><th key={col} className="border-b border-white/10 px-3 py-2 font-medium text-slate-500">{col}</th>)}</tr></thead><tbody>{q.fixturePreview.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j} className="border-b border-white/5 px-3 py-2 text-slate-400">{cell===null?'NULL':String(cell)}</td>)}</tr>)}</tbody></table></div></div>}</div>}</div>
   <textarea value={answer} onKeyDown={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.altKey)setKeystrokes(v=>v+1)}} onChange={e=>{setAnswer(e.target.value);events.current.push({type:'EDIT',at:new Date().toISOString()})}} className="mt-6 min-h-[55vh] w-full resize-none rounded-lg border border-white/10 bg-black/30 p-4 font-mono text-sm leading-6 text-slate-200 outline-none placeholder:text-slate-700" spellCheck={false} autoCorrect="off" autoCapitalize="off" placeholder="Write your solution here…" aria-label="Your answer"/>
   {error&&<p className="mt-3 text-sm text-rose-300" role="alert">{error}</p>}
   <div className="mt-4 flex items-center justify-between gap-4"><span className="text-xs text-slate-600">{keystrokes} keystrokes recorded · The next question adapts to your response and time.</span><button className="btn-primary" disabled={!answer.trim()||submitting||seconds===0} onClick={submit}>{submitting?'Evaluating…':'Submit & continue →'}</button></div>
  </div>
 </div></div>;
}
export default function AssessmentWorkspacePage(){return <Suspense fallback={<div className="min-h-screen bg-[#071019] text-slate-100 p-4 sm:p-6"><div className="mx-auto max-w-3xl"><p className="eyebrow">ASSESSMENT WORKSPACE</p><h1 className="mt-2 text-2xl font-semibold">Loading…</h1></div></div>}><Workspace/></Suspense>}