'use client';
import{useState}from'react';
import type{UnifiedCase}from'@/lib/verification/unified-types';
export function TriPaneInspector({testCase}:{testCase:UnifiedCase}){
 const[view,setView]=useState<'SPLIT'|'DIFF_ONLY'>('SPLIT');
 if(!testCase.isPublic)return <div className="rounded-xl border border-white/10 bg-slate-950 p-8 text-center"><div className={testCase.status==='AC'?'text-emerald-300':'text-rose-300'}>{testCase.status==='AC'?'✓ Hidden Assertion Verified':'✗ Hidden Boundary Failure'}</div><p className="mt-2 text-xs text-slate-500">Hidden inputs and canonical outputs remain masked.</p></div>;
 const panes=view==='DIFF_ONLY'?'grid-cols-2':'grid-cols-3';
 const table=(title:string,data?:{columns:string[];rows:Record<string,unknown>[]},accent='text-slate-400',highlight=false)=><div className="min-w-0"><div className={'mb-2 text-[10px] font-bold uppercase tracking-wider '+accent}>{title}</div><div className="max-h-64 overflow-auto rounded border border-white/10"><table className="w-full text-left text-[10px]"><thead className="sticky top-0 bg-slate-900"><tr>{data?.columns.map(c=><th key={c} className="whitespace-nowrap px-2 py-1.5 text-slate-500">{c}</th>)}</tr></thead><tbody>{data?.rows.map((row,i)=><tr key={i} className="border-t border-white/5">{data.columns.map(c=><td key={c} className={'whitespace-nowrap px-2 py-1.5 '+(highlight&&testCase.diff&&testCase.diff.rowIndex===i+1&&testCase.diff.columnName.toLowerCase()===c.toLowerCase()?'bg-rose-950 text-rose-300 font-semibold':'text-slate-300')}>{String(row[c]??'NULL')}</td>)}</tr>)}</tbody></table></div></div>;
 return <div className="rounded-xl border border-white/10 bg-slate-950 overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-3 py-2"><span className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">Visual Discrepancy Inspector</span><div className="flex gap-1"><button onClick={()=>setView('SPLIT')} className="rounded border border-white/10 px-2 py-1 text-[10px] text-slate-400">Tri-Pane</button><button onClick={()=>setView('DIFF_ONLY')} className="rounded border border-white/10 px-2 py-1 text-[10px] text-slate-400">Diff Only</button></div></div><div className={'grid '+panes+' gap-3 p-3'}>{view==='SPLIT'&&table('Input Fixture',testCase.inputFixturePreview)}{table('Expected (Canonical)',testCase.expectedOutputPreview,'text-emerald-400')}{table('Your Output',testCase.actualOutputPreview,'text-slate-400',true)}</div>{testCase.diff&&<div className="border-t border-white/10 px-3 py-3 text-[11px]"><span className="text-rose-300 font-semibold">Mismatch:</span> row {testCase.diff.rowIndex}, column <span className="text-rose-300">{testCase.diff.columnName}</span> · expected <span className="text-emerald-300">{testCase.diff.expectedValue}</span> · actual <span className="text-rose-300">{testCase.diff.actualValue}</span></div>}{testCase.diagnosticAdvice&&<div className="border-t border-white/10 bg-rose-950/20 px-3 py-3 text-[11px] text-rose-200"><span className="font-semibold">Diagnosis:</span> {testCase.diagnosticAdvice}</div>}</div>;
}