'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {AppShell} from '@/components/AppShell';
import {CANONICAL_CAPABILITY_TAXONOMY} from '@/lib/taxonomy';
import {AlertCircle,CheckCircle2,ChevronRight,RefreshCw,Search,ShieldCheck} from 'lucide-react';

type CandidateCapability={slug:string;name:string;state:string;last_demonstrated_at:string|null;evidence_count:number;verification_tier:string};
type CandidateMatch={candidate_id:string;masked_handle:string;visibility:string;capabilities:CandidateCapability[]};
type Organization={employerAccountId:string;organizationName:string;role:string};

export default function HiringSearch(){
 const [selectedSlugs,setSelectedSlugs]=useState(['sql.window_functions','python.concurrency.rate_limiter']);
 const [candidates,setCandidates]=useState<CandidateMatch[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null); const [authenticated,setAuthenticated]=useState(false); const [organizations,setOrganizations]=useState<Organization[]>([]); const [organizationId,setOrganizationId]=useState(''); const [switching,setSwitching]=useState(false);
 useEffect(()=>{fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.session?.role==='employer'){setAuthenticated(true);setOrganizations(d.session.employerMemberships||[]);setOrganizationId(d.session.employerAccountId||'');}else setError('Please sign in with an employer account to access candidate search.');}).catch(()=>setError('Unable to resolve employer session.'));},[]);
 useEffect(()=>{if(!authenticated||!organizationId||!selectedSlugs.length){setCandidates([]);return;} let cancelled=false; setLoading(true); setError(null); fetch('/api/hiring/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({required_capability_slugs:selectedSlugs,require_fresh:true})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to query candidates');if(!cancelled)setCandidates(d.candidates||[]);}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)}); return()=>{cancelled=true};},[authenticated,organizationId,selectedSlugs]);
 const switchOrganization=async(id:string)=>{setSwitching(true);setError(null);try{const r=await fetch('/api/auth/organization',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({employer_account_id:id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to switch organization');setOrganizationId(id);}catch(e){setError(e instanceof Error?e.message:'Unable to switch organization')}finally{setSwitching(false)}};
 const toggle=(slug:string)=>setSelectedSlugs(v=>v.includes(slug)?v.filter(x=>x!==slug):[...v,slug]);
 return <AppShell role="employer"><div className="max-w-6xl space-y-6"><div className="border-b border-white/10 pb-4 flex items-center justify-between"><div><p className="eyebrow">HIRING WORKSPACE</p><h1 className="mt-2 text-3xl font-semibold flex items-center gap-2"><Search className="h-5 w-5 text-emerald-400"/>Verified candidate search</h1><p className="mt-2 text-sm text-slate-500">Exact capability requirements. Results are factual and unranked.</p></div><div className="hidden sm:flex items-center gap-1.5 text-xs text-slate-400"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Evidence-first</div></div>
 {organizations.length>1&&<section className="panel p-5"><div className="label">Organization context</div><p className="mt-1 text-xs text-slate-500">Select the organization whose hiring authorization should be used for this workspace.</p><select aria-label="Organization" value={organizationId} disabled={switching} onChange={e=>switchOrganization(e.target.value)} className="input mt-3"><option value="">Select organization</option>{organizations.map(o=><option key={o.employerAccountId} value={o.employerAccountId}>{o.organizationName} · {o.role}</option>)}</select></section>}
 <section className="panel p-5"><div className="flex justify-between"><div className="label">Required capabilities · AND</div><span className="text-[11px] font-mono text-slate-600">Selected: {selectedSlugs.length}</span></div><div className="mt-3 flex flex-wrap gap-2">{CANONICAL_CAPABILITY_TAXONOMY.map(n=>{const on=selectedSlugs.includes(n.slug);return <button key={n.slug} onClick={()=>toggle(n.slug)} className={`rounded-lg border px-3 py-2 text-sm flex items-center gap-1.5 ${on?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':'border-white/5 text-slate-500 hover:border-white/10'}`}><CheckCircle2 className={`h-3.5 w-3.5 ${on?'text-emerald-400':'text-slate-700'}`}/>{n.name}</button>})}</div></section>
 <div className="flex items-center justify-between text-xs text-slate-500"><span>{candidates.length} candidates satisfying all {selectedSlugs.length} required capabilities</span>{loading&&<span className="flex items-center gap-1.5"><RefreshCw className="h-3.5 w-3.5 animate-spin"/>Querying evidence</span>}</div>
 {error&&<div className="panel p-4 text-sm text-red-300 flex items-center gap-2"><AlertCircle className="h-4 w-4"/>{error}</div>}
 {!loading&&!error&&selectedSlugs.length>0&&!candidates.length&&organizationId&&<div className="panel p-12 text-center text-sm text-slate-500">No candidates possess active demonstrated proof for all selected capabilities.</div>}
 <div className="grid gap-4 md:grid-cols-2">{candidates.map(c=><article key={c.candidate_id} className="panel p-5 space-y-4"><div className="flex justify-between gap-3"><div><div className="font-medium">{c.masked_handle}</div><div className="mt-1 text-xs text-slate-600">PII masked · {c.visibility}</div></div><span className="pill pill-good">DEMONSTRATED</span></div><div className="space-y-2">{c.capabilities.map(cap=><div key={cap.slug} className="flex justify-between gap-3 rounded-lg border border-white/5 p-3"><span className="text-sm">{cap.name}</span><span className="text-[11px] font-mono text-slate-500">{cap.verification_tier.replaceAll('_',' ')}</span></div>)}</div><Link className="btn-ghost w-full justify-center" href={`/hiring/candidates/${c.candidate_id}/dossier`}>Inspect dossier <ChevronRight className="h-3.5 w-3.5"/></Link></article>)}</div></div></AppShell>;
}
