'use client';
import {useEffect,useMemo,useState}from'react';
import {AppShell}from'@/components/AppShell';

type Arena={id:string;title:string;domain:string;experienceLevel:string;scheduledStart:string|null;durationMinutes:number;arenaType:'OPEN'|'PRIVATE_1V1'|'TEAM';maxParticipants:number;currentParticipants:number;creatorStack:string;creator:{name:string;handle:string};parity:{status:string;candidateTheta:number|null;targetTheta:number;disparity:number;note:string};canJoin:boolean};
const domains=[['ALL','All'],['sql-window-functions','SQL'],['python-concurrency','Python'],['java.concurrency_memory','Java'],['linux.process_signals','Linux'],['docker.container_internals','Docker']];
const levels=[['ALL','All'],['BEGINNER','Beginner'],['INTERMEDIATE','Intermediate'],['ADVANCED','Advanced']];
const types=[['ALL','All'],['OPEN','Open'],['PRIVATE_1V1','1v1'],['TEAM','Team']];

export default function Hackathons(){
 const[arenas,setArenas]=useState<Arena[]>([]),[show,setShow]=useState(false),[joinArena,setJoinArena]=useState<Arena|null>(null),[joinStack,setJoinStack]=useState('python'),[message,setMessage]=useState('');
 const[filters,setFilters]=useState({domain:'ALL',experience_level:'ALL',arena_type:'ALL',open_only:true});
 const[form,setForm]=useState({title:'',domain:'sql-window-functions',experienceLevel:'INTERMEDIATE',arenaType:'OPEN',declaredLanguage:'python',scheduledStart:'',durationMinutes:60,problemSuggestion:''});
 const load=()=>{const q=new URLSearchParams({domain:filters.domain,experience_level:filters.experience_level,arena_type:filters.arena_type,open_only:String(filters.open_only)});return fetch('/api/hackathons/arenas?'+q.toString(),{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load arenas');setArenas(d.arenas||[])}).catch(e=>setMessage(e instanceof Error?e.message:'Unable to load arenas'));};
 useEffect(()=>{void load()},[filters.domain,filters.experience_level,filters.arena_type,filters.open_only]);
 const submit=async()=>{setMessage('Creating arena…');const r=await fetch('/api/hackathons',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?'Arena created. Participants must review and agree before PATIMA schedules it.':d.error||'Unable to create arena');if(r.ok){setShow(false);await load()}};
 const formatStart=(v:string|null)=>v?new Date(v).toLocaleString(): 'Start time to be agreed';
 const join=async()=>{if(!joinArena)return;setMessage('Joining arena…');const r=await fetch('/api/hackathons/'+joinArena.id+'/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({declaredLanguage:joinStack})});const d=await r.json();setMessage(r.ok?'Joined arena. Review the terms and accept before scheduling.':d.error||'Unable to join arena');if(r.ok){setJoinArena(null);await load()}};
 return <AppShell><p className="eyebrow">TECHNICAL HACKATHONS</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="mt-2 text-3xl font-semibold">Arena Discovery</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Discover open technical arenas, compare them with your verified capability profile, and join only after reviewing the parity and platform rules.</p></div><button className="btn-primary" onClick={()=>setShow(true)}>Create Arena</button></div>{message&&<div className="panel mt-5 p-4 text-sm text-slate-400">{message}</div>}
 <div className="panel mt-6 p-4"><div className="label">FILTERS</div><div className="mt-3 grid gap-3 md:grid-cols-4">{[['domain','Domain',domains],['experience_level','Tier',levels],['arena_type','Type',types]].map(([key,label,opts]:any)=><label key={key} className="text-xs text-slate-500">{label}<select className="input mt-1" value={(filters as any)[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{opts.map((o:any)=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>)}<label className="flex items-end gap-2 text-xs text-slate-400 pb-2"><input type="checkbox" checked={filters.open_only} onChange={e=>setFilters({...filters,open_only:e.target.checked})}/> Open slots only</label></div></div>
 <div className="mt-6 space-y-4">{!arenas.length?<div className="panel p-8 text-center text-sm text-slate-500">No matching arenas are currently available. Adjust the filters or create an arena for others to discover.</div>:arenas.map(a=><article key={a.id} className="panel p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="label">{a.arenaType} · {a.experienceLevel}</div><h2 className="mt-2 text-lg font-medium">{a.title}</h2><p className="mt-1 text-xs text-slate-500">{a.domain} · {a.durationMinutes} minutes · {a.currentParticipants}/{a.maxParticipants} participants</p><p className="mt-1 text-xs text-slate-500">Created by @{a.creator.handle} · Starts {formatStart(a.scheduledStart)}</p></div><button className="btn-primary text-xs" disabled={!a.canJoin} onClick={()=>setJoinArena(a)}>Review & Join</button></div><div className={'mt-4 rounded-lg border p-4 text-xs leading-5 '+(a.parity.status==='COMPATIBLE'?'border-emerald-500/20 bg-emerald-950/10 text-emerald-100/70':'border-amber-500/20 bg-amber-950/10 text-amber-100/70')}><b>{a.parity.status==='COMPATIBLE'?'Parity audit':'Capability disparity warning'}:</b> {a.parity.note}</div><div className="mt-3 text-xs text-slate-500">Creator stack: {a.creatorStack}. PATIMA authors fixtures, public tests, hidden tests, runtime limits and server arbitration after agreement.</div></article>)}</div>
 {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="panel w-full max-w-xl p-6"><h2 className="text-lg font-semibold">Propose Hackathon Arena</h2><p className="mt-2 text-xs leading-5 text-slate-500">You suggest the capability and problem direction; PATIMA constructs the actual fixtures, limits and hidden conditions after participant agreement.</p><div className="mt-5 grid gap-3"><label className="text-xs text-slate-500">Arena type<select className="input mt-1" value={form.arenaType} onChange={e=>setForm({...form,arenaType:e.target.value})}><option value="OPEN">Open Public Arena</option><option value="PRIVATE_1V1">Private 1v1</option><option value="TEAM">Team Squad</option></select></label><label className="text-xs text-slate-500">Challenge title<input className="input mt-1" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="text-xs text-slate-500">Capability / domain<select className="input mt-1" value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}>{domains.filter(x=>x[0]!=='ALL').map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="text-xs text-slate-500">Target capability tier<select className="input mt-1" value={form.experienceLevel} onChange={e=>setForm({...form,experienceLevel:e.target.value})}>{levels.filter(x=>x[0]!=='ALL').map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label><label className="text-xs text-slate-500">Your declared stack<input className="input mt-1" value={form.declaredLanguage} onChange={e=>setForm({...form,declaredLanguage:e.target.value})}/></label><label className="text-xs text-slate-500">Proposed start<input type="datetime-local" className="input mt-1" value={form.scheduledStart} onChange={e=>setForm({...form,scheduledStart:e.target.value})}/></label><label className="text-xs text-slate-500">Problem proposal / prompt suggestion <span className="text-slate-600">(optional)</span><textarea className="input mt-1 min-h-24" value={form.problemSuggestion} onChange={e=>setForm({...form,problemSuggestion:e.target.value})}/></label><div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn-primary" onClick={()=>void submit()}>Create Arena</button></div></div></div></div>}
 </AppShell>;
}
