import assert from'node:assert/strict';import{directPool}from'../lib/db';
async function run(){const a=await directPool.connect(),b=await directPool.connect();const ids:string[]=[];try{
 const u=await a.query(`SELECT u.id FROM user_accounts u WHERE u.role='candidate' AND u.status='ACTIVE' AND NOT EXISTS(SELECT 1 FROM assessment_sessions s WHERE s.user_id=u.id AND s.domain='sql-window-functions' AND s.status='IN_PROGRESS') ORDER BY u.created_at LIMIT 1`);if(!u.rows[0])throw new Error('No clean active candidate available.');
 const userId=u.rows[0].id as string;const node=await a.query(`SELECT id FROM capability_nodes WHERE slug='sql.window_functions' LIMIT 1`);if(!node.rows[0])throw new Error('SQL capability node is not configured.');
 const insert=(c:any)=>c.query(`INSERT INTO assessment_sessions(user_id,target_role,seniority,domain_slug,capability_node_id,domain,experience_level,current_step,status,started_at,expires_at,last_activity_at,selected_question_count,selected_duration_minutes) VALUES($1,'Data Engineer','MID','sql-window-functions',$2,'sql-window-functions','INTERMEDIATE',1,'IN_PROGRESS',clock_timestamp(),clock_timestamp()+interval '25 minutes',clock_timestamp(),5,8) RETURNING id`,[userId,node.rows[0].id]);
 console.log('[GATE 1] Two connections race on one candidate/domain...');const [x,y]=await Promise.allSettled([insert(a),insert(b)]);const ok=[x,y].filter(z=>z.status==='fulfilled') as PromiseFulfilledResult<any>[];const bad=[x,y].filter(z=>z.status==='rejected') as PromiseRejectedResult[];assert.equal(ok.length,1);assert.equal(bad.length,1);assert.equal((bad[0].reason as any)?.code,'23505');ids.push(ok[0].value.rows[0].id);
 const q=await a.query(`SELECT count(*)::int AS count FROM assessment_sessions WHERE user_id=$1 AND domain='sql-window-functions' AND status='IN_PROGRESS'`,[userId]);assert.equal(Number(q.rows[0].count),1);console.log('PASS: exactly one active session; loser gets unique_violation 23505.');
 console.log('[GATE 2] Cleanup...');await a.query('DELETE FROM active_question_reservations WHERE session_id=ANY($1::uuid[])',[ids]);await a.query('DELETE FROM assessment_adaptive_logs WHERE session_id=ANY($1::uuid[])',[ids]);await a.query('DELETE FROM assessment_sessions WHERE id=ANY($1::uuid[])',[ids]);console.log('PASS: cleanup complete.');console.log('ALL 2 SESSION-START RACE GATES PASSED.');
}finally{if(ids.length){try{await a.query('DELETE FROM active_question_reservations WHERE session_id=ANY($1::uuid[])',[ids])}catch{}try{await a.query('DELETE FROM assessment_adaptive_logs WHERE session_id=ANY($1::uuid[])',[ids])}catch{}try{await a.query('DELETE FROM assessment_sessions WHERE id=ANY($1::uuid[])',[ids])}catch{}}a.release();b.release();await directPool.end()}}
run().catch(e=>{console.error('GATE FAILURE:',e);process.exit(1)});
