'use client';
import {useEffect,useState}from'react';
import Link from'next/link';
import {AppShell}from'@/components/AppShell';
import {StatusPill}from'@/components/StatusPill';
import {TechnicalRecordSummary,TechnicalRecordMetrics}from'@/components/TechnicalRecordSummary';

type Evidence={evidenceId:string;capability:string;state:string;verificationTier:string;recordedAt:string;summary:string;context?:string|null;artifactCode?:string|null;testTrace:unknown[];peerReviewSummary?:string|null;artifactSha256?:string|null;merkleRoot?:string|null;attestationSignature?:string|null;astFingerprint?:unknown;behavioralAssertions?:unknown;executionTraceDigest?:string|null;assessmentSessionId?:string|null;executionRunCount:number;latestExecutionTimeMs:number|null};

export default function EvidencePage(){
 const[metrics,setMetrics]=useState<TechnicalRecordMetrics>({assessmentsCompleted:0,evidenceRecords:0,demonstratedCount:0,developingCount:0});
 const[e,setE]=useState<Evidence[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[open,setOpen]=useState<string|null>(null);
 useEffect(()=>{Promise.all([fetch('/api/candidate/overview',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Unable to load technical record');return r.json()}),fetch('/api/candidate/evidence',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load evidence');return d})]).then(([o,d])=>{if(o.metrics)setMetrics(o.metrics);setE(d.evidence||[])}).catch(err=>setError(err instanceof Error?err.message:'Unable to load technical record')).finally(()=>setLoading(false));},[]);
 const stateA=metrics.assessmentsCompleted===0&&metrics.evidenceRecords===0;
 const stateB=metrics.assessmentsCompleted>0&&metrics.evidenceRecords===0;
 return <AppShell>
  <p className="eyebrow">TECHNICAL DOSSIER</p><h1 className="mt-2 text-3xl font-semibold">Inspectable evidence records</h1>
  <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Assessments record evaluation events. Evidence records are durable, server-verified observations derived from those events.</p>
  <div className="mt-6"><TechnicalRecordSummary metrics={metrics}/></div>
  {error&&<div className="panel mt-6 p-5 text-sm text-rose-300">{error}</div>}
  {!loading&&!error&&stateA&&<div className="panel mt-6 p-8 text-center border-dashed"><h2 className="text-base font-semibold text-slate-200">No Technical Evaluation on Record</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-slate-500">You have not completed an adaptive assessment or challenge. Begin an assessment to create inspectable technical evidence.</p><Link href="/app/assessments" className="btn-primary mt-5 inline-flex">Browse Assessments</Link></div>}
  {!loading&&!error&&stateB&&<div className="panel mt-6 p-8 text-center border-amber-500/30 bg-amber-950/10"><h2 className="text-base font-semibold text-amber-200">Assessment Completed — Evidence Not Recorded</h2><p className="mx-auto mt-2 max-w-lg text-xs leading-5 text-slate-400">You have completed {metrics.assessmentsCompleted} assessment session(s), but no evidence record is currently linked to them. Review the assessment results or retake it if needed.</p><div className="mt-5 flex justify-center gap-3"><Link href="/app/results" className="btn-ghost text-xs">View Assessment Results</Link><Link href="/app/assessments" className="btn-primary text-xs">Take Another Assessment</Link></div></div>}
 {!loading&&!error&&!stateA&&!stateB&&<div className="mt-6 space-y-4">{e.map(x=>{const expanded=open===x.evidenceId;return <article key={x.evidenceId} className="panel overflow-hidden"><button type="button" onClick={()=>setOpen(expanded?null:x.evidenceId)} className="w-full p-5 text-left"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-medium">{x.capability}</h2><p className="mt-1 text-xs text-slate-600">Observed {new Date(x.recordedAt).toLocaleString()} · {x.verificationTier} · Evidence #{x.evidenceId.slice(0,8)}</p></div><StatusPill value={x.state}/></div><div className="mt-4 grid gap-3 md:grid-cols-4 text-xs"><div><span className="label">Verification</span><p className="mt-1 text-slate-300">{x.verificationTier}</p></div><div><span className="label">Execution runs</span><p className="mt-1 text-slate-300">{x.executionRunCount}</p></div><div><span className="label">Latest runtime</span><p className="mt-1 text-slate-300">{x.latestExecutionTimeMs==null?'—':x.latestExecutionTimeMs+' ms'}</p></div><div><span className="label">Artifact integrity</span><p className="mt-1 truncate font-mono text-slate-400">{x.artifactSha256||'not recorded'}</p></div></div></button>{expanded&&<div className="border-t border-white/5 p-5 space-y-5"><section><div className="label">What was observed</div><p className="mt-2 text-sm leading-6 text-slate-300">{x.summary}</p>{x.context&&<p className="mt-2 text-xs leading-5 text-slate-500">{x.context}</p>}</section><section><div className="label">Attested artifact</div>{x.artifactCode?<pre className="mt-2 max-h-80 overflow-auto rounded-lg border border-white/5 bg-black/20 p-4 text-xs leading-6">{x.artifactCode}</pre>:<p className="mt-2 text-sm text-slate-500">No code artifact was persisted for this record.</p>}</section><section><div className="label">Verification trace</div><pre className="mt-2 max-h-72 overflow-auto rounded-lg border border-white/5 bg-black/20 p-4 text-xs leading-5">{JSON.stringify({testTrace:x.testTrace,behavioralAssertions:x.behavioralAssertions,astFingerprint:x.astFingerprint,executionTraceDigest:x.executionTraceDigest},null,2)}</pre></section><section><div className="label">Integrity</div><div className="mt-2 grid gap-2 font-mono text-[11px] text-slate-400"><p>Evidence ID: {x.evidenceId}</p><p>Assessment session: {x.assessmentSessionId||'—'}</p><p>Artifact Integrity Fingerprint (SHA-256): {x.artifactSha256||'not recorded'}</p><p>Merkle root: {x.merkleRoot||'not recorded'}</p><p>Digital signature: {x.attestationSignature||'not recorded'}</p></div></section></div>}</article>})}</div>}
  {loading&&<div className="panel mt-6 p-8 text-center text-sm text-slate-500">Loading technical record...</div>}
 </AppShell>;
}
