'use client';
import Link from 'next/link';
import {AppShell} from '@/components/AppShell';
import {assessments} from '@/lib/personal';

const expanded=[
  ...assessments.map(a=>({slug:a.slug,title:a.title,duration:a.duration,description:a.description,capability:a.capability,status:'AVAILABLE' as const})),
  {slug:'java.concurrency_memory',title:'Java Concurrency & Memory Model',duration:'15–20 min',capability:'Java Concurrency & Memory',domain:'Systems Engineering',description:'Reason about thread safety, volatile semantics, synchronized primitives, and deadlock isolation.',status:'AVAILABLE' as const},
  {slug:'linux.process_signals',title:'Linux Systems & Signals',duration:'15–20 min',capability:'Linux Systems & Process Control',domain:'Systems Engineering',description:'Reason about process lifecycle, file descriptors, signals, and pipe-based IPC debugging.',status:'AVAILABLE' as const},
  {slug:'docker.container_internals',title:'Docker & Container Mechanics',duration:'15–20 min',capability:'Docker & Container Mechanics',domain:'Infrastructure & DevOps',description:'Reason about cgroups, namespace isolation, multi-stage builds, and layer caching.',status:'AVAILABLE' as const},
  {slug:'spark.distributed_execution',title:'Apache Spark Streaming & Optimization',duration:'20–25 min',capability:'Apache Spark',domain:'Distributed Data',description:'Reason about partition skew, memory management, shuffle tuning, and recovery semantics.',status:'COMING_SOON' as const},
];

export default function Assessments(){return <AppShell><p className="eyebrow">ASSESSMENTS</p><h1 className="mt-2 text-3xl font-semibold">Choose a technical probe</h1><p className="mt-2 text-sm text-slate-500">Each available probe is a focused capability investigation, not a score-based quiz.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{expanded.map(a=>a.status==='AVAILABLE'?<Link href={`/app/assessments/${a.slug}`} key={a.slug} className="panel block p-5"><div className="flex justify-between text-xs text-slate-500"><span className="text-emerald-300">{a.capability}</span><span>{a.duration}</span></div><h2 className="mt-4 text-xl font-medium">{a.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{a.description}</p><div className="mt-5 text-xs text-emerald-300">Start assessment →</div></Link>:<div key={a.slug} className="panel block p-5 opacity-75"><div className="flex justify-between text-xs text-slate-500"><span>{a.capability}</span><span className="rounded border border-amber-800/60 bg-amber-950/60 px-2 py-0.5 text-[10px] text-amber-400">Coming Soon</span></div><h2 className="mt-4 text-xl font-medium">{a.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{a.description}</p><div className="mt-5 text-xs text-slate-600">Level B Runner in Lab Testing</div></div>)}</div></AppShell>}
