import{NextResponse}from'next/server';

const SAFE_CLIENT_ERRORS=new Set([
 'UNAUTHORIZED','MISSING_REQUIRED_FIELDS','VARIANT_NOT_FOUND_OR_LEASE_EXPIRED',
 'SESSION_NOT_IN_PROGRESS','SUBMISSION_VERIFICATION_FAILED','RESERVATION_EXPIRED_OR_MISMATCH',
 'STEP_ALREADY_FINALIZED','INSUFFICIENT_QUESTION_INVENTORY_FOR_SPECIFICATION',
 'NO_AUTHORED_TEST_CASES_CONFIGURED_FOR_VARIANT','TRACK_DISABLED_PENDING_ISOLATED_HARNESS',
 'SESSION_ALREADY_ACTIVE','NO_ACTIVE_QUESTION_RESERVATION','QUESTION_RESERVATION_MISMATCH','VERIFICATION_REQUIRED_BEFORE_ADVANCE','VERIFICATION_FAILED_NO_ADVANCE','STEP_ALREADY_FINALIZED'
]);

const STATUS_BY_ERROR:Record<string,number>={
 UNAUTHORIZED:401,MISSING_REQUIRED_FIELDS:400,VARIANT_NOT_FOUND_OR_LEASE_EXPIRED:404,
 SESSION_ALREADY_ACTIVE:409,RESERVATION_EXPIRED_OR_MISMATCH:409,NO_ACTIVE_QUESTION_RESERVATION:409,QUESTION_RESERVATION_MISMATCH:409,VERIFICATION_REQUIRED_BEFORE_ADVANCE:409,VERIFICATION_FAILED_NO_ADVANCE:422,STEP_ALREADY_FINALIZED:409,
 SESSION_NOT_IN_PROGRESS:409,SUBMISSION_VERIFICATION_FAILED:422,
 INSUFFICIENT_QUESTION_INVENTORY_FOR_SPECIFICATION:409,
 NO_AUTHORED_TEST_CASES_CONFIGURED_FOR_VARIANT:422,TRACK_DISABLED_PENDING_ISOLATED_HARNESS:422
};

export function handleRouteError(err:unknown,routeContext:string):NextResponse{
 const rawMessage=err instanceof Error?err.message:'UNKNOWN_ERROR';
 console.error(`[API_ERROR] [${routeContext}]`,err);
 if(SAFE_CLIENT_ERRORS.has(rawMessage))return NextResponse.json({error:rawMessage},{status:STATUS_BY_ERROR[rawMessage]??422});
 return NextResponse.json({error:'INTERNAL_SERVER_ERROR',code:'UNEXPECTED_PROCESSING_FAULT'},{status:500});
}
