'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';
import {UserPlus} from 'lucide-react';

export default function Signup(){
 const r=useRouter(),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const res=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not create account');r.replace('/app');}catch(x){setError(x instanceof Error?x.message:'Could not create account');}finally{setLoading(false);}};
 return <main className="patima-public px-5 py-8 sm:px-6"><div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-md flex-col justify-center"><Link href="/" className="mb-5 self-start text-sm font-medium text-slate-500 hover:text-red-600">← PATIMA</Link><div className="panel p-6 sm:p-8"><div className="mb-7 flex items-start gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-red-50"><UserPlus className="h-5 w-5 text-red-600"/></div><div><h1 className="text-xl font-semibold tracking-tight text-slate-950">Create your PATIMA account</h1><p className="mt-1.5 text-sm leading-6 text-slate-500">Start building an inspectable technical evidence record.</p></div></div><form onSubmit={submit} className="space-y-5"><label className="block text-xs font-medium text-slate-600">Name<input className="input h-11" value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label><label className="block text-xs font-medium text-slate-600">Email<input className="input h-11" value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com"/></label><label className="block text-xs font-medium text-slate-600">Password<input className="input h-11" value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className="alert">{error}</div>}<button disabled={loading} className="btn-primary h-11 w-full justify-center">{loading?'Creating account…':'Create candidate account'}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link className="font-medium text-red-600 hover:text-red-700" href="/login">Sign in</Link></p></div></div></main>;
}
