'use client';
import Link from 'next/link';
import {FormEvent,useState} from 'react';
import {useRouter} from 'next/navigation';
import {UserPlus} from 'lucide-react';

export default function Signup(){
 const r=useRouter(),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const res=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not create account');r.replace('/app');}catch(x){setError(x instanceof Error?x.message:'Could not create account');}finally{setLoading(false);}};
 return <main className="min-h-screen bg-[#071019] px-5 py-8 text-slate-100 sm:px-6"><div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-md flex-col justify-center"><Link href="/" className="mb-5 self-start text-sm text-slate-500 transition hover:text-slate-300">← PATIMA</Link><div className="rounded-xl border border-white/10 bg-slate-900/70 p-6 shadow-sm sm:p-8"><div className="mb-7 flex items-start gap-3"><UserPlus className="mt-0.5 h-5 w-5 shrink-0 text-emerald-300"/><div><h1 className="text-xl font-semibold tracking-tight">Create your PATIMA account</h1><p className="mt-1.5 text-sm leading-6 text-slate-500">Start building an inspectable technical evidence record.</p></div></div><form onSubmit={submit} className="space-y-5"><label className="block text-xs font-medium text-slate-400">Name<input className="mt-1.5 block h-11 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-slate-100 outline-none placeholder:text-slate-600 focus:border-slate-500 focus:ring-1 focus:ring-slate-500/30" value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label><label className="block text-xs font-medium text-slate-400">Email<input className="mt-1.5 block h-11 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-slate-100 outline-none placeholder:text-slate-600 focus:border-slate-500 focus:ring-1 focus:ring-slate-500/30" value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com"/></label><label className="block text-xs font-medium text-slate-400">Password<input className="mt-1.5 block h-11 w-full rounded-lg border border-white/10 bg-slate-950 px-3 text-sm text-slate-100 outline-none focus:border-slate-500 focus:ring-1 focus:ring-slate-500/30" value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className="rounded-lg border border-red-900/70 bg-red-950/40 px-3 py-2.5 text-xs leading-5 text-red-300">{error}</div>}<button disabled={loading} className="inline-flex h-11 w-full items-center justify-center rounded-lg bg-white px-4 text-sm font-medium text-slate-950 transition hover:bg-slate-200 disabled:cursor-not-allowed disabled:opacity-50">{loading?'Creating account…':'Create candidate account'}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already have an account? <Link className="text-emerald-300 hover:text-emerald-200" href="/login">Sign in</Link></p></div></div></main>;
}
