'use client';
import {useEffect,useState} from 'react';
import {AppShell} from '@/components/AppShell';

type Session={name:string;email:string;handle:string;role:string};
type Evidence={capability:string;state:string;verification:string;observedAt:string|null;evidenceCount:number};
type Overview={metrics:TechnicalRecordMetrics;stats:{demonstrated:number;developing:number;completed:number};evidence:Evidence[];activeAssessment?:{domain:string;experienceLevel:string;currentStep:number;questionCount:number;expiresAt:string;targetRole:string|null}|null};

export default function Profile(){
 const[s,setS]=useState<Session|null>(null),[o,setO]=useState<Overview|null>(null);
 useEffect(()=>{Promise.all([fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()),fetch('/api/candidate/overview',{cache:'no-store'}).then(r=>r.json())]).then(([a,b])=>{setS(a.session);setO(b)}).catch(()=>{});},[]);
 return <AppShell><p className="eyebrow">PROFILE</p><h1 className="mt-2 text-3xl font-semibold">Your professional identity</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">A factual profile derived from your authenticated account and persisted PATIMA evidence. Skills are not self-declared as verified capability.</p>
  {o&&<div className="mt-6"><TechnicalRecordSummary metrics={o.metrics}/></div>}
  <div className="mt-6 grid gap-4 lg:grid-cols-2"><section className="panel p-6"><h2 className="font-medium">Identity & verification</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><div className="label">Real name</div><p className="mt-1">{s?.name||'—'}</p></div><div><div className="label">Account handle</div><p className="mt-1 font-mono">@{s?.handle||'—'}</p></div><div><div className="label">Primary contact email</div><p className="mt-1 break-all text-slate-300">{s?.email||'—'}</p></div><div><div className="label">Verification tier</div><p className="mt-1 text-slate-400">Provisional Email</p></div><div className="sm:col-span-2"><div className="label">Shareable profile</div><p className="mt-1 font-mono text-xs text-slate-400">/p/{s?.handle||'—'}</p></div></div></section>
  <section className="panel p-6"><h2 className="font-medium">Verified capability summary</h2><div className="mt-5 grid grid-cols-3 gap-3"><div><div className="label">Demonstrated</div><p className="mt-2 text-2xl font-semibold">{o?.stats.demonstrated??0}</p></div><div><div className="label">Developing</div><p className="mt-2 text-2xl font-semibold">{o?.stats.developing??0}</p></div><div><div className="label">Evidence records</div><p className="mt-2 text-2xl font-semibold">{o?.metrics.evidenceRecords??0}</p></div></div><p className="mt-5 text-xs leading-5 text-slate-500">Counts come from authenticated server records; no client-local or seeded demonstration data is used here.</p></section></div>
  <section className="panel mt-4 p-6"><div className="flex items-center justify-between"><h2 className="font-medium">Verified technical matrix</h2><a href="/app/evidence" className="text-xs text-sky-300">Inspect evidence →</a></div>{!o?.evidence?.length?<p className="mt-4 text-sm text-slate-500">No capability evidence has been recorded yet.</p>:<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-white/10 text-slate-500"><th className="p-3">Capability</th><th className="p-3">State</th><th className="p-3">Verification</th><th className="p-3">Observed</th><th className="p-3">Evidence</th></tr></thead><tbody>{o.evidence.map(e=><tr key={e.capability} className="border-b border-white/5"><td className="p-3 text-slate-200">{e.capability}</td><td className="p-3">{e.state}</td><td className="p-3 text-slate-400">{e.verification}</td><td className="p-3 text-slate-400">{e.observedAt||'—'}</td><td className="p-3 text-slate-400">{e.evidenceCount}</td></tr>)}</tbody></table></div>}</section>
  <section className="panel mt-4 p-6"><h2 className="font-medium">Assessment & challenge history</h2>{o?.activeAssessment?<div className="mt-4 rounded-lg border border-sky-500/20 bg-sky-500/5 p-4 text-sm"><div className="font-medium">{o.activeAssessment.domain}</div><p className="mt-1 text-xs text-slate-500">{o.activeAssessment.experienceLevel} · step {o.activeAssessment.currentStep}/{o.activeAssessment.questionCount}</p><a className="mt-3 inline-block text-xs text-sky-300" href="/app/assessments/workspace">Resume assessment →</a></div>:<p className="mt-4 text-sm text-slate-500">No active assessment. Completed evidence is available in the Evidence Dossier.</p>}</section>
 </AppShell>;
}
