import {randomBytes,scryptSync} from 'node:crypto';
import process from 'node:process';
import pg from 'pg';
const {Pool}=pg;
if(!process.env.DATABASE_URL){console.error('[PATIMA] DATABASE_URL is required for seeding.');process.exit(1);}
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:1});
const hashPassword=(password)=>{const salt=randomBytes(16).toString('hex');return `scrypt$${salt}$${scryptSync(password,salt,64).toString('hex')}`;};
const candidateId='c9a01f42-8812-4211-b0e1-482910482910', employerUserId='u0000000-0000-0000-0000-000000000002', employerId='e0000000-0000-0000-0000-000000000001';
const nodes=[['11111111-1111-1111-1111-111111111111','sql.window_functions','SQL Window Functions'],['22222222-2222-2222-2222-222222222222','python.concurrency.rate_limiter','Python Concurrency & Rate Limiting'],['33333333-3333-3333-3333-333333333333','distributed_systems.consensus.raft','Distributed Consensus (Raft)'],['44444444-4444-4444-4444-444444444444','data_engineering.streaming','Stream Processing & Deduplication']];
try{
 await pool.query('BEGIN');
 for(const [id,slug,name] of nodes){await pool.query(`INSERT INTO capability_nodes(id,slug,name) VALUES($1,$2,$3) ON CONFLICT(slug) DO UPDATE SET name=EXCLUDED.name`,[id,slug,name]);await pool.query(`INSERT INTO capability_decay_profiles(capability_node_id,half_life_days) VALUES($1,180) ON CONFLICT(capability_node_id) DO NOTHING`,[id]);}
 await pool.query(`INSERT INTO user_accounts(id,name,email,handle,role,password_hash,email_verified_at,status) VALUES($1,'PATIMA Candidate','candidate@patima.test','candidate-9821','candidate',$2,clock_timestamp(),'ACTIVE') ON CONFLICT(id) DO UPDATE SET password_hash=EXCLUDED.password_hash,status='ACTIVE'`,[candidateId,hashPassword('CandidateSecret123!')]);
 await pool.query(`INSERT INTO user_accounts(id,name,email,handle,role,password_hash,email_verified_at,status) VALUES($1,'PATIMA Recruiter','recruiter@patima.test','recruiter-acme','employer',$2,clock_timestamp(),'ACTIVE') ON CONFLICT(id) DO UPDATE SET password_hash=EXCLUDED.password_hash,status='ACTIVE'`,[employerUserId,hashPassword('RecruiterSecret123!')]);
 await pool.query(`INSERT INTO employer_accounts(id,organization_name,identity_status) VALUES($1,'Acme Engineering Corp','VERIFIED') ON CONFLICT(id) DO NOTHING`,[employerId]);
 await pool.query(`INSERT INTO employer_members(employer_account_id,user_account_id,role) VALUES($1,$2,'RECRUITER') ON CONFLICT(employer_account_id,user_account_id) DO UPDATE SET role='RECRUITER'`,[employerId,employerUserId]);
 await pool.query(`INSERT INTO candidate_visibility_settings(user_id,visibility,accepting_contact_requests) VALUES($1,'PUBLIC',true) ON CONFLICT(user_id) DO UPDATE SET visibility='PUBLIC',accepting_contact_requests=true`,[candidateId]);
 for(const [id,slug] of nodes.slice(0,2)){await pool.query(`INSERT INTO user_capability_states(user_id,capability_node_id,state,last_demonstrated_at,last_observed_at,evidence_count) VALUES($1,$2,'DEMONSTRATED',clock_timestamp()-INTERVAL '2 days',clock_timestamp(),1) ON CONFLICT(user_id,capability_node_id) DO UPDATE SET state='DEMONSTRATED',last_demonstrated_at=EXCLUDED.last_demonstrated_at,last_observed_at=EXCLUDED.last_observed_at,evidence_count=GREATEST(user_capability_states.evidence_count,1)`,[candidateId,id]);await pool.query(`INSERT INTO evidence_records(user_id,capability_node_id,verification_tier,summary,context,artifact_code,test_trace,peer_review_summary,artifact_sha256,merkle_root,attestation_signature) SELECT $1,$2,'CLIENT_EVALUATED',$3,'Controlled PATIMA verification session','def example():\n    return True','[]'::jsonb,NULL,NULL,NULL,NULL WHERE NOT EXISTS (SELECT 1 FROM evidence_records WHERE user_id=$1 AND capability_node_id=$2)`,[candidateId,id,`Demonstrated ${slug} in an isolated verification session.`]);}
 await pool.query('COMMIT');console.log('[PATIMA] Hiring verification seed ready. Candidate and employer credentials are for local/controlled testing only.');
}catch(error){await pool.query('ROLLBACK');throw error;}finally{await pool.end();}
