'use client';
import Link from 'next/link'; import {useEffect,useState} from 'react'; import {AppShell} from '@/components/AppShell';

type RequestRow={id:string;candidate_user_id:string;handle:string;role_title:string;message_body:string;status:string;created_at:string;expires_at:string|null;responded_at:string|null;released_email:string|null};

export default function HiringRequests(){
 const[requests,setRequests]=useState<RequestRow[]>([]); const[loading,setLoading]=useState(true); const[error,setError]=useState('');
 useEffect(()=>{let alive=true;(async()=>{try{const r=await fetch('/api/hiring/contact/requests',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load contact requests');if(alive)setRequests(d.requests||[]);}catch(e){if(alive)setError(e instanceof Error?e.message:'Unable to load contact requests')}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 return <AppShell role="employer"><div className="max-w-4xl"><p className="eyebrow">HIRING WORKSPACE</p><h1 className="mt-2 text-3xl font-semibold">Outbound contact requests</h1><p className="mt-2 text-sm text-slate-500">Requests are scoped to the selected employer organization. Candidate contact details appear only after explicit consent.</p>{loading?<div className="panel mt-6 p-8 text-sm text-slate-500">Loading requests…</div>:error?<div className="panel mt-6 p-5 text-sm text-red-300">{error}</div>:requests.length===0?<div className="panel mt-6 p-8 text-sm text-slate-500">No contact requests yet.</div>:<div className="mt-6 space-y-3">{requests.map(r=><div key={r.id} className="panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><Link href={`/hiring/candidates/${r.candidate_user_id}/dossier`} className="font-medium hover:underline">@{r.handle}</Link><div className="mt-1 text-xs text-slate-600">{r.role_title}</div></div><span className={`pill ${r.status==='ACCEPTED'?'pill-ok':r.status==='PENDING_CANDIDATE_APPROVAL'?'pill-warn':'pill-muted'}`}>{r.status.replaceAll('_',' ')}</span></div><p className="mt-4 text-sm leading-6 text-slate-400">{r.message_body}</p><div className="mt-4 border-t border-white/5 pt-3 text-xs text-slate-600">{r.released_email?<span className="text-emerald-300">Contact authorized: {r.released_email}</span>:r.status==='PENDING_CANDIDATE_APPROVAL'?'Awaiting candidate approval.':'Contact details were not released.'}<span className="ml-3">{new Date(r.created_at).toLocaleString()}</span></div></div>)}</div>}</div></AppShell>}
